[formatter.cabal-fmt]
command = "cabal-fmt"
excludes = []
includes = ["*.cabal"]
options = ["--inplace"]

[formatter.nix]
command = "nixfmt"
excludes = []
includes = ["*.nix"]
options = []

[formatter.ormolu]
command = "ormolu"
excludes = []
includes = ["*.hs"]
options = ["-i", "-c", "--ghc-opt", "-XBangPatterns", "--ghc-opt", "-XPatternSynonyms", "--ghc-opt", "-XTypeApplications"]

[formatter.toml-sort]
command = "toml-sort"
excludes = []
includes = ["*.toml"]
options = ["-i"]

[formatter.typos]
command = "typos"
excludes = []
includes = ["*"]
options = ["--write-changes"]
