# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build and deploy site

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v30

      - name: Build site
        shell: sh
        run: |
          nix build .#website
          cp --recursive --dereference --no-preserve=mode,ownership result dist

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=website

      - name: Upload pages artifact
        uses: actions/upload-artifact@v4
        with:
          name: pages
          path: dist
          retention-days: 7
          if-no-files-found: error
